version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: armv7
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
    binary: stylus-remapper-armv7
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
  - id: aarch64
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
    binary: stylus-remapper-aarch64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

upx:
  - enabled: true
    compress: best
    lzma: true

archives:
  - format: tar.gz
    name_template: "{{ .Binary }}"
    files:
      - none*

release:
  extra_files:
    - glob: qmd/*.qmd

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
